### ISSUE TITLE
Optimization for large images?

### ISSUE THREAD

**Issue by BioinfoTongLI** [BBQuercus/deepBlink#129]
Hello there!

Thanks for building this awesome tool!
I really like the way your pipeline works. Very brilliant! 

I am raising this request as I encountered the out-of-memory issue whe running on a relatively large images (30k * 60k) as described below.

**Is your feature request related to a problem? Please describe.**
Out-of-memory for large images.
![image](https://user-images.githubusercontent.com/9748580/125646472-232e7c94-538e-4d5e-b463-4f6f57ef44f3.png)

**Describe the solution you'd like**
Internal optimization if possible? Otherwise, a higher level data chunking should also be fine (such as using lazy loading/parallelization of [dask.map_overlap](https://docs.dask.org/en/latest/array-overlap.html) ?)

**Additional context**
OS: ubuntu
RAM: 330Gb
CPU: 30 cores

I am very open to discussions related to this.

Best,
Tong

**Comment by BBQuercus** [comment]
Hi Tong,

Thanks for the feedback 😄. I might have found a possible source of the error (TensorFlow automatically creates a batch size of 32 when predicting; given your large image sizes of around 17GB each, allocating this much memory probably exceeds your available RAM).

It would be great if you could verify if this is the source of error:
* Find your local deepblink installation (`pip show deepblink` -> `Location` / `deepblink`)
* Open up the `inference.py` file
* Replace line 37 from `pred = model.predict(image_pad[None, ..., None]).squeeze()` to `pred = model.predict(image_pad[None, ..., None], batch_size=1).squeeze()`
* Retry predicting on your large image

If this works, I'll add this change in one of the next pull requests. Otherwise tiling is probably the easiest option since mapping and TensorFlow aren't the best friends:
```python
import deepblink as pink
import numpy as np
import skimage.io
import skimage.util

# Load image and model
image = skimage.io.imread("image.tif")
model = pink.io.load_model("model.h5")

# Tile image into 1000x1000 patches with steps of 1000 to avoid multiple detections of the same spots
stepsize = 1000
windows = skimage.util.view_as_windows(image, window_shape=(1000, 1000), step=stepsize)

preds = []
for n_row, row in enumerate(windows):
     for n_col, col in enumerate(row):
         # Predict current window
         raw_pred = deepblink.inference.predict(col, model).T
         # Add position back in large image
         pred = np.array([
             raw_pred[0] + (n_row * stepsize),
             raw_pred[1] + (n_col * stepsize)
         ]).T
         preds.append(pred)

coords = np.concatenate(preds)
```

Best,
Bastian

**Comment by BioinfoTongLI** [comment]
Hi Bastian, 

Thanks a lot for the quick reply!
Unfortunately that didn't seem to work. Still the same error and I can see RAM saturation in less than 2 mins.

The python script look nice. Are you planning on making the tiling version as an option in the next PR?

Best,
Tong

**Comment by BBQuercus** [comment]
Hmm... this is the first time we had to deal with this large images. If more people encounter similar issues, we'll have to think about where / how to include it (either as a normal option or as standalone example notebook).

**Comment by BioinfoTongLI** [comment]
Sure, that makes sense! I will wirte a python script to wrap it for now.
Mnay thanks for your help! Please feel free to close this.

**Comment by BBQuercus** [comment]
No problem and thanks for bringing it to our attention!
