### ISSUE TITLE
tiff images not allowed in predict

### ISSUE THREAD

**Issue by SosUts** [BBQuercus/deepBlink#142]
**Describe the bug**
tiff images are supported in `io.py` but not in `_predict.py`.
https://github.com/BBQuercus/deepBlink/blob/5ccc67bcf43d4dc4de550b7c1aad1add89758f92/deepblink/io.py#L20-L21
https://github.com/BBQuercus/deepBlink/blob/5ccc67bcf43d4dc4de550b7c1aad1add89758f92/deepblink/cli/_argparse.py#L16

**Expected behavior**
Both tiff and tif images are supported.

**Screenshots**
When passing tiff image to predict, it returns
```python
deepblink predict: error: argument -i/--input:
Input file must have extension ('tif', 'jpeg', 'jpg', 'png'). 'hoge.tiff' does not.
```

**Versions:**
 - OS: Windows10
 - Python Version: 3.7.0
 - deepBlink Version: 0.1.3

**Comment by SosUts** [comment]
All we have to do is change the input file extension, but I've shared it with you just in case!

**Comment by BBQuercus** [comment]
Hey. Thanks for letting us know! It was originally designed like this to avoid strange behaviour with different shapes and metadata when users provided `tiff` files but this should no longer be the case. If you want to start using the CLI on `tiff` files right away just `pip install -e .` the cloned repo since we won't be creating a new release right away.
